[package]
name = "nio"
version = "0.1.0"
authors = ["n4o847"]
edition = "2021"

[workspace]
members = [
    "crates/*",
    "playground/crate",
]

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
nio_parser = { path = "crates/parser" }
nio_wasm = { path = "crates/wasm" }
