[package]
name = "nio"
version = "0.1.0"
authors = ["n4o847"]
edition = "2021"

[workspace]
members = ["crates/parser"]

[dependencies]
clap = "3.0.14"
nio_parser = { path = "crates/parser", version = "0.1.0" }
