[package]
name = "nio_parser"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = "0.19.7"
regex = "1.5.5"

[dev-dependencies]
insta = { version = "1.12.0", features = ["glob"] }
