[package]
name = "nio_parser"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"

[dev-dependencies]
insta = { version = "1.12.0", features = ["glob"] }
